name: gcm-filters-docs
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - numpy
  - scipy
  - xarray
  - dask  # necessary for basic_filtering.rst
  - matplotlib
  - numpydoc
  - sphinx
  - sphinx-book-theme
  - sphinx-copybutton
  - myst-parser
  - myst-nb
  - sphinxcontrib-srclinks
  - setuptools
