name: gcm-filters-docs
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - xarray
  - dask
  - matplotlib
  - numpydoc
  - sphinx
  - ipython
  - nbconvert
  - nbformat
  - ipykernel # not strictly necessary but this is nice to run notebooks in this env to test
  - pandoc
  - jupyter_client
  - sphinx-book-theme
  - sphinx-copybutton
  - myst-parser
  - myst-nb
  - sphinxcontrib-srclinks
  - intake
  - intake-xarray
  - s3fs
  - cartopy
  - pooch>=1.5.0
  - cupy
